# SPDX-License-Identifier: ISC
# SPDX-FileCopyrightText: (c) 2019 Anil Madhavapeddy <anil@recoil.org>
name: Builds, tests & co

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'pull_request' || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    permissions:
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
        ocaml-compiler:
          - 5
          - 4
          - ocaml-variants.5.3.0+options,ocaml-option-flambda
          - ocaml-variants.4.14.2+options,ocaml-option-flambda
          - ocaml-variants.5.2.0+ox

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install autoconf (macos)
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install autoconf

      - name: Set-up OCaml (ox)
        if: ${{ contains(matrix.ocaml-compiler, '+ox') }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-repositories: |
            default: "git+https://github.com/ocaml/opam-repository.git"
            ox: "git+https://github.com/oxcaml/opam-repository.git"

      - name: Set-up OCaml (non-ox)
        if: ${{ !contains(matrix.ocaml-compiler, '+ox') }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-opam@v3
